language: node_js

node_js:
 - 10.15.0

branches:
  only:
  - master

install:
 - npm install -g istanbul
 - npm install

before_script:

script:
  - npm run build
  - npm run test

after_script:
  - cp ./dist/* ./docs/ -r

